spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}

    properties:
      security.protocol: SSL

      ssl.keystore.location: ${KEYSTORE_LOCATION}
      ssl.keystore.password: ${KEYSTORE_PASSWORD}
      ssl.keystore.type: ${KEYSTORE_TYPE}

      ssl.truststore.location: ${TRUSTSTORE_LOCATION}
      ssl.truststore.password: ${TRUSTSTORE_PASSWORD}
      ssl.truststore.type: ${TRUSTSTORE_TYPE}

      ssl.endpoint.identification.algorithm: https

    consumer:
      auto-offset-reset: earliest
      group-id: consumer-group-id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.malex.configuration.kafka.KafkaCustomDeserializer
      properties:
        spring.json.trusted.packages: com.malex
        spring.json.value.default.type: com.malex.Event

kafka:
  consumer:
    topic: events-topic